name: master_test

on:
  push:
    branches: [ master ]

jobs:
  master_test:
    runs-on: macos-latest
    steps:
      - name: Checkout project
        uses: actions/checkout@v2      
      - name: Setup python
        uses: actions/setup-python@v1
        with:
          python-version: '3.8'
      - name: Install deps
        run: pip install meson ninja
      - name: Configure
        run: meson build && chmod 777 /Users/runner/work/nnstreamer-build-macos/nnstreamer-build-macos/build/subprojects/macos-bison-binary/bison.py
      - name: Build
        run: ninja -C build
